### ISSUE TITLE
chrome driver issue..

### ISSUE THREAD

**Issue by Chalia1** [celebi-pkg/flight-analysis#25]
can you please help :( im getting this error:

**WARNING:root:Can not find chromedriver for currently installed chrome version.
Scraping Objects:   0%|**                                                                                                                                     | 0/1 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "/Users/chalinfernando/Downloads/flight-analysis-main/test.py", line 4, in <module>
    ScrapeObjects(results)
  File "/Users/chalinfernando/Downloads/flight-analysis-main/src/google_flight_analysis/scrape.py", line 39, in ScrapeObjects
    debug = [obj._scrape_data(driver) for obj in tqdm(objs, desc="Scraping Objects")]
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chalinfernando/Downloads/flight-analysis-main/src/google_flight_analysis/scrape.py", line 377, in _scrape_data
    results = [self._get_results(url, self._date[i], driver) for i, url in enumerate(self._url)]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chalinfernando/Downloads/flight-analysis-main/src/google_flight_analysis/scrape.py", line 405, in _get_results
    flights = _Scrape._clean_results(results, date)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chalinfernando/Downloads/flight-analysis-main/src/google_flight_analysis/scrape.py", line 424, in _clean_results
    flights = [Flight(date, res3[matches[i]:matches[i+1]]) for i in range(len(matches)-1)]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/google_flight_analysis/flight.py", line 29, in __init__
    self._parse_args(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/google_flight_analysis/flight.py", line 157, in _parse_args
    self._classify_arg(arg)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/google_flight_analysis/flight.py", line 134, in _classify_arg
    self._price = int(arg[1:].replace(',',''))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
**ValueError: invalid literal for int() with base 10: 'A$755'**

**Comment by Chalia1** [comment]
fixed it
