### ISSUE TITLE
Program crashes on 4 digit price

### ISSUE THREAD

**Issue by dffdff2423** [celebi-pkg/flight-analysis#8]
Hi, I noticed a small issue: the program seems to crash on some flights, based off of the stacktrace I think it might be due to the fact that google flights inserts a comma in 4 diget numbers. 

I noticed the issue with this snippet:   
```python
from src.google_flight_analysis.scrape import *
result = Scrape('CHI', 'BJS', '2023-05-28', '2023-07-15')
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/flight-analysis/src/google_flight_analysis/scrape.py", line 33, in __call__
    self._data = self._scrape_data()
  File "/tmp/flight-analysis/src/google_flight_analysis/scrape.py", line 135, in _scrape_data
    leave_result = self._get_results(self._make_url(self._date_leave, leave = True), driver)
  File "/tmp/flight-analysis/src/google_flight_analysis/scrape.py", line 170, in _get_results
    flights = self._clean_results(results)
  File "/tmp/flight-analysis/src/google_flight_analysis/scrape.py", line 191, in _clean_results
    flights = [Flight(self._date_leave, res3[matches[i]:matches[i+1]]) for i in range(len(matches)-1)]
  File "/tmp/flight-analysis/src/google_flight_analysis/scrape.py", line 191, in <listcomp>
    flights = [Flight(self._date_leave, res3[matches[i]:matches[i+1]]) for i in range(len(matches)-1)]
  File "/tmp/flight-analysis/src/google_flight_analysis/flight.py", line 29, in __init__
    self._parse_args(*args)
  File "/tmp/flight-analysis/src/google_flight_analysis/flight.py", line 155, in _parse_args
    self._classify_arg(arg)
  File "/tmp/flight-analysis/src/google_flight_analysis/flight.py", line 125, in _classify_arg
    self._co2 = int(arg.split()[0])
ValueError: invalid literal for int() with base 10: '1,007'
```

**Comment by kcelebi** [comment]
Hi, thank you for pointing this out and taking the time to look at it. This is a fix that I've already implemented for the next patch, so I will be closing this issue and the PR.
